### PR TITLE
Add decorative colours

### PR DESCRIPTION
**Pull request by nadonomy**
This PR adds decorative text & bg colours to Light & Dark. Aside from a general sense check, it would be great to review specifically:

1. High contrast: Is anything missing? They automatically appeared in the Figma style panel, but a sense check would be great. 
2. The line diff in `tokens/$themes.json`: This looks noisy, but is caused by creating the styles in Figma from Token Studio. I think it's fine (guessing the tool is just refreshing a bunch of auto generated stuff) but let me know if anything looks wonky.
 
Once this is LGTM'd, I'll:

1. Circle back to Figma to push [these working styles](https://www.figma.com/file/PpKepmHKGikp33Ql7iivbn?node-id=22:2763&mode=design#684301916) to the shared library, to make available for the designers.
3. Figure out how to sync these changes with Themer.
4. Add documentation on all the steps I needed to take to get through this.

### CODE REVIEW

**Comment by pixlwave** [comment]
The sync looks good from what I can tell.
1. All of the referenced colours have HC variants, so we should basically get that for free.
Screenshot 2024-01-30 at 10 00 20 am
2. Yeah looks fine to me. If something went wrong, the entire file would likely get new IDs.

What's missing though is another commit that runs `yarn build` to generate the tokens for Android/iOS/Web to consume.

**Comment by nadonomy** [comment]
@pixlwave ack. Should that happen before or after the PR is merged?

In either case, it'd be great if we can settle on & document a workflow where the developer merging actions. So far this PR was authored via the Token Studio GUI. Want to avoid designers needing dev environments to add tokens.

**Comment by pixlwave** [comment]
> it'd be great if we can settle on & document a workflow where the developer merging actions.

Ok yep, looking at https://github.com/element-hq/compound-design-tokens/pull/31 this is exactly what happened.

**Comment by nadonomy** [comment]
> > it'd be great if we can settle on & document a workflow where the developer merging actions.
> 
> Ok yep, looking at #31 this is exactly what happened.

Aha. :) Would you mind adding dev notes to https://github.com/element-hq/element-internal/issues/547 as a new issue comment? If so, I can include when I PR more documentation to Storybook.

**Comment by pixlwave** [comment]
> Should that happen before or after the PR is merged?

Definitely before merging. It makes sense for the reviewer to generate the assets and then provide any feedback in case something about the updates is fine for tokens studio, but is an issue with the style dictionary.

**Review by pixlwave — APPROVED** [review]
Alright I've added the assets to the PR and they look good. Are you happy for me to merge now @nadonomy or is there anything else you need to try out first?

**Comment by nadonomy** [comment]
@pixlwave I think let's just merge.

I have outstanding points to R&D, but intuition would be to sync/release those changes by pulling from main/post merge anyway.

**Comment by pixlwave** [comment]
Done 🎉

**Pull request merged**
