### PR TITLE
Update icons from Figma.

### PR DESCRIPTION
**Pull request by pixlwave**
@Velin92 noticed that the `unpin` icon was missing, so I decided to do a complete sync with Figma. This has resulted in `calendar` and `room` also being added and a handful of seemingly minor tweaks to existing icons - the export was done with the usual `Monochrome` preset and only about 30% of the icons have changes so may just be refinements to the path algorithm in the plugin.

The second commit tweaks the generation script as (possibly following the style dictionary update?) we weren't generating the icons for Swift or Kotlin. I have *zero* idea why editing `getIOSConfig` fixed Kotlin, but it did 🤷‍♂️.

### CODE REVIEW

**Comment by jmartinesp** [comment]
> The second commit tweaks the generation script as (possibly following the style dictionary update?) we weren't generating the icons for Swift or Kotlin. I have zero idea why editing getIOSConfig fixed Kotlin, but it did 🤷‍♂️.

That's not scary at all 🫠 .

**Review by jmartinesp — APPROVED** [review]
All the icons were imported fine in Compound Android locally, LGTM!

**Comment by robintown** [comment]
Uh oh. We could make our CI wipe the `assets` folder clean before running the generation step to catch those kinds of things.

**Comment by pixlwave** [comment]
> Uh oh. We could make our CI wipe the `assets` folder clean before running the generation step to catch those kinds of things.

Yeah sounds reasonable to me.

**Pull request merged**
